version: "3"
services: 
  redis:
    container_name: "redis_express_gateway"
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    volumes:
      - ./redis/:/bitnami/redis/data
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
